//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVEntityProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCVEntityEntities : DbContext
    {
        public DBCVEntityEntities()
            : base("name=DBCVEntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Adres> Tbl_Adres { get; set; }
        public virtual DbSet<Tbl_Çalışmalarım> Tbl_Çalışmalarım { get; set; }
        public virtual DbSet<Tbl_Hakkında> Tbl_Hakkında { get; set; }
        public virtual DbSet<Tbl_iletisim> Tbl_iletisim { get; set; }
        public virtual DbSet<Tbl_Yetenekler> Tbl_Yetenekler { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
    }
}
